export const FETCH_SUJETS = "FETCH_SUJETS"

export const SEND_NEW_POST = "ADD_NEW_POST"
export const FETCH_POST = "FETCH_POST"
export const DELETE_POST = "DELETE_POST"

export const LOG_IN = "LOG_IN"
export const LOG_OUT = "LOG_OUT"

export const SET_VISA = "SET_VISA"

export const FETCH_NOTIFICATION = "FETCH_NOTIFICATION"
export const SEND_NEW_NOTIFICATION = "SEND_NEW_NOTIFICATION"
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION"
